/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as IndexRouteImport } from './routes/index'

const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conversas': typeof ConversasRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conversas': typeof ConversasRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conversas': typeof ConversasRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conversas' | '/pesquisa' | '/relatorios' | '/simulacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conversas' | '/pesquisa' | '/relatorios' | '/simulacao'
  id:
    | '__root__'
    | '/'
    | '/conversas'
    | '/pesquisa'
    | '/relatorios'
    | '/simulacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConversasRoute: typeof ConversasRoute
  PesquisaRoute: typeof PesquisaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SimulacaoRoute: typeof SimulacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConversasRoute: ConversasRoute,
  PesquisaRoute: PesquisaRoute,
  RelatoriosRoute: RelatoriosRoute,
  SimulacaoRoute: SimulacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
